# Generated by Django 3.2.13 on 2022-05-22 22:04

from django.db import migrations, models
import winwinmarket.validators


class Migration(migrations.Migration):

    dependencies = [
        ('winwinmarket', '0003_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=40, null=True, validators=[winwinmarket.validators.validate_no_special_characters]),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=20, null=True, validators=[winwinmarket.validators.validate_no_special_characters]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True, unique=True, validators=[winwinmarket.validators.validate_no_special_characters]),
        ),
    ]
