# Generated by Django 3.2.13 on 2022-05-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winwinmarket', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
