# Generated by Django 3.2.13 on 2022-05-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winwinmarket', '0006_post_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
